openapi: 3.0.1
info:
  title: Application
  description: Generated at 22/11/2023 00:40:59. This is the swagger 
    ui based on the open api 3.0 specification of the Application
  version: 1.0.0 created by the flask swagger generator.
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: '/'
paths:
  '/swagger/dist/{filename}':
    get:
      tags:
      - swagger_ui
      operationId: 'static'
      parameters:
      - in: path
        name: filename
        schema:
          type: string
        description: None
        required: True
  '/swagger/{path}':
    get:
      tags:
      - swagger_ui
      operationId: 'show'
      parameters:
      - in: path
        name: path
        schema:
          type: string
        description: None
        required: True
  '/swagger/':
    get:
      tags:
      - swagger_ui
      operationId: 'show'
  '/':
    get:
      tags:
      - None
      operationId: 'metrics'
  '/tables':
    get:
      tags:
      - None
      operationId: 'get_tables'
      parameters:
      - in: query
        name: None
        schema:
          type: string
        description: None
        required: False
        allowReserved: False
      responses:
        '200':
          $ref: '#/components/responses/get_tables_response'
  '/free-tables':
    get:
      tags:
      - None
      operationId: 'get_free_tables'
      parameters:
      - in: query
        name: None
        schema:
          type: string
        description: None
        required: False
        allowReserved: False
      responses:
        '200':
          $ref: '#/components/responses/get_free_tables_response'
  '/reservations':
    get:
      tags:
      - None
      operationId: 'handle_reservations'
      responses:
        '200':
          $ref: '#/components/responses/handle_reservations_response'
    post:
      tags:
      - None
      operationId: 'handle_reservations'
      responses:
        '200':
          $ref: '#/components/responses/handle_reservations_response'
    put:
      tags:
      - None
      operationId: 'handle_reservations'
      responses:
        '200':
          $ref: '#/components/responses/handle_reservations_response'
components:
  responses:
    get_tables_response:
      description: get_tables response
      content:
         application/json:
             schema:
                 $ref: '#/components/schemas/get_tables_response_schema'
    get_free_tables_response:
      description: get_free_tables response
      content:
         application/json:
             schema:
                 $ref: '#/components/schemas/get_free_tables_response_schema'
    handle_reservations_response:
      description: handle_reservations response
      content:
         application/json:
             schema:
                 $ref: '#/components/schemas/handle_reservations_response_schema'
  schemas:
    get_tables_response_schema:
      type: object
      properties:
        tables:
          type: array  
          items:
            type: object
    get_free_tables_response_schema:
      type: object
      properties:
        tables:
          type: array  
          items:
            type: object
    handle_reservations_response_schema:
      type: object
      properties:
        reservations:
          type: array  
          items:
            type: object
